version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpressvol:/var/www
    depends_on:
      - wordpress
    networks:
      - network

  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpressvol:/var/www
    networks:
      - network
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./MariaDB
      dockerfile: Dockerfile
    volumes:
      - MariaDBvol:/var/lib/mysql
    networks:
      - network

volumes:
  wordpressvol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/pedro/Desktop/data/wordpress'

  MariaDBvol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/pedro/Desktop/data/mysql'

networks:
  network:
    driver: bridge
