version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpressvol:/var/www/
    depends_on:
      - wordpress
    networks:
      - network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpressvol:/var/www/
    networks:
      - network
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    restart: on-failure

  redis:
    container_name: redis
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    volumes:
      - redisVol:/var/lib/redis
    networks:
      - network
    restart: on-failure

  vsftp:
    container_name: ftp
    build:
      context: ./bonus/vsftpd
      dockerfile: Dockerfile
    networks:
      - network
    ports:
      - 20-21:20-21
    volumes:
      - wordpressvol:/home/ppaulo-d
    env_file:
      - .env
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/MariaDB
      dockerfile: Dockerfile
    volumes:
      - MariaDBvol:/var/lib/mysql
    networks:
      - network
    restart: on-failure
    env_file:
      - .env

  adminer:
    container_name: adminer
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    networks:
      - network
    restart: on-failure

  monitoring:
    container_name: monitoring
    build:
      context: ./bonus/monitoring
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - monitoringVol:/moni

volumes:
  wordpressvol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/pedro/Desktop/data/www'

  MariaDBvol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/pedro/Desktop/data/mysql'
  
  redisVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/pedro/Desktop/data/redis'

  monitoringVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/pedro/Desktop/data/monitoring'

networks:
  network:
    driver: bridge
